// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChEyfxnkITgBmrFxXF866Zvwm_Y8T2Vv4',
    appId: '1:515598149607:web:dcc3718730030bcaa2ff42',
    messagingSenderId: '515598149607',
    projectId: 'reddit-clone-24',
    authDomain: 'reddit-clone-24.firebaseapp.com',
    storageBucket: 'reddit-clone-24.appspot.com',
    measurementId: 'G-H1W4DQYZG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRpYEzvTzygnjer7g8Mp8a1gKUPsz6cNs',
    appId: '1:515598149607:android:715b33ffacba34cca2ff42',
    messagingSenderId: '515598149607',
    projectId: 'reddit-clone-24',
    storageBucket: 'reddit-clone-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvaqyoqXN_1JgGnm3cb1NxcEVJJkQnJcI',
    appId: '1:515598149607:ios:a50c096988bcec4aa2ff42',
    messagingSenderId: '515598149607',
    projectId: 'reddit-clone-24',
    storageBucket: 'reddit-clone-24.appspot.com',
    androidClientId: '515598149607-p406ih4uv2eg1dvjocgevcqbou6d1ldc.apps.googleusercontent.com',
    iosClientId: '515598149607-a5muioqihhloces1ftlejatujlij3stb.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvaqyoqXN_1JgGnm3cb1NxcEVJJkQnJcI',
    appId: '1:515598149607:ios:44a53f8bb73a5f55a2ff42',
    messagingSenderId: '515598149607',
    projectId: 'reddit-clone-24',
    storageBucket: 'reddit-clone-24.appspot.com',
    androidClientId: '515598149607-p406ih4uv2eg1dvjocgevcqbou6d1ldc.apps.googleusercontent.com',
    iosClientId: '515598149607-7d3925qt3qmu7hgjf0ajh3hqrepgcmno.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
